export const canvasData = {
  objectId: 'canvas',
  objectType: 'canvas',
  group: [
    {
      label: '对象',
      value: 'object',
    },
    {
      label: '规格',
      value: 'specs',
    },
  ],
  object: [
    {
      id: 'id',
      name: 'ID',
      value: 'canvas',
      valueBase: 'string',
      editor: 0,
    },
    {
      id: 'name',
      name: '名称',
      value: '画布',
      valueBase: 'string',
      editor: 0,
    },
    {
      id: 'version',
      name: '版本',
      value: 'v1.0.0',
      valueBase: 'string',
      editor: 0,
    },
    {
      id: 'input',
      name: '输入对象',
      value: [
        {
          id: 'attribute1',
          type: 'AttributeNode',
          x: 188,
          y: 121,
          properties: {
            id: 'M19a58601ce9',
            width: 240,
            height: 174,
            group: 'object',
            icon: 'attrIco',
            type: 'attribute',
            label: '设备状态',
            deviceName: '灯光控制网络继电器-2#',
            location: '主楼 > 2层 > 配电间',
            valueType: 'bool',
            value: 'false',
            unit: '',
          },
        },
        {
          id: 'variable2',
          type: 'VariableNode',
          x: 233,
          y: 303,
          properties: {
            id: 'variable2',
            width: 240,
            height: 74,
            group: 'object',
            icon: 'variableIco',
            type: 'variable',
            valueType: 'number',
            value: '44',
          },
        },
      ],
      valueBase: 'string',
      editor: 0,
      fromInput: 'inputArray',
    },
  ],
  specs: [
    {
      id: 'width',
      name: '宽度',
      value: 'auto',
      valueBase: 'string',
      editor: 0,
    },
    {
      id: 'height',
      name: '高度',
      value: 'auto',
      valueBase: 'string',
      editor: 0,
    },
  ],
};

// 物模型节点
export const modelData = {
  objectId: '',
  objectType: 'model',
  group: [
    {
      label: '对象',
      value: 'object',
    },
    {
      label: '规格',
      value: 'specs',
    },
    {
      label: '属性',
      value: 'attribute',
    },
    {
      label: '数据',
      value: 'data',
    },
  ],
  object: [
    {
      id: 'id',
      name: 'ID',
      value: '',
      valueBase: 'string',
      editor: 1,
      fromInput: 'input',
    },
    {
      id: 'label',
      name: '名称',
      value: '',
      valueBase: 'string',
      editor: 0,
    },
    {
      id: 'type',
      name: '类型',
      value: '',
      valueBase: 'string',
      editor: 0,
    },
  ],
  specs: [
    {
      id: 'width',
      name: '宽度',
      value: '',
      valueBase: 'int',
      editor: 1,
      fromInput: 'input',
    },
    {
      id: 'height',
      name: '高度',
      value: '',
      valueBase: 'int',
      editor: 1,
      fromInput: 'input',
    },
    {
      id: 'width',
      name: '最小宽度',
      value: '240',
      valueBase: 'int',
      editor: 0,
    },
    {
      id: 'height',
      name: '最小高度',
      value: '174',
      valueBase: 'int',
      editor: 0,
    },
    {
      id: 'x',
      name: 'x坐标',
      value: '',
      valueBase: 'int',
      editor: 1,
      fromInput: 'input',
    },
    {
      id: 'y',
      name: 'y坐标',
      value: '',
      valueBase: 'int',
      editor: 1,
      fromInput: 'input',
    },
  ],
  attribute: [
    {
      id: 'input',
      name: '输入对象',
      value: [],
      valueBase: 'array',
      editor: 0,
      fromInput: 'inputArray',
    },
    {
      id: 'output',
      name: '输出对象',
      value: [],
      valueBase: 'array',
      editor: 0,
      fromInput: 'inputArray',
    },
  ],
  data: [
    {
      id: 'bind',
      name: '绑定设备',
      value: '',
      valueBase: 'object',
      editor: 1,
      fromInput: 'bindDevice',
    },
    {
      id: 'location',
      name: '空间位置',
      value: '',
      valueBase: 'string',
      editor: 0,
    },
    {
      id: 'valueType',
      name: '输出类型',
      value: '',
      valueBase: 'boolean',
      editor: 1,
      fromInput: 'select',
      fromOptions: [
        {
          label: 'int',
          value: 'int',
        },
        {
          label: 'number',
          value: 'number',
        },
        {
          label: 'string',
          value: 'string',
        },
        {
          label: 'boolean',
          value: 'boolean',
        },
      ],
    },
    {
      id: 'value',
      name: '输出值',
      value: '',
      valueBase: 'string',
      editor: 0,
    },
    {
      id: 'unit',
      name: '计量单位',
      value: '',
      valueBase: 'string',
      editor: 1,
      fromInput: 'input',
    },
  ],
  node: {},
};
