export const groupList = [
  {
    label: '数据对象',
    value: 'object',
  },
  {
    label: '条件判断',
    value: 'judgement',
  },
  {
    label: '计算符',
    value: 'compute',
  },
  {
    label: '日期时间',
    value: 'timer',
  },
  {
    label: '函数方法',
    value: 'function',
  },
  {
    label: '执行输出',
    value: 'option',
  },
  {
    label: '操作方法',
    value: 'execute',
  },
];

export const componentList = [
  {
    id: 100,
    label: '物模型属性',
    type: 'attribute',
    group: 'object',
    nodeType: 'AttributeNode',
    iconClass: 'attrIco',
  },
  {
    id: 101,
    label: '物模型服务',
    type: 'service',
    group: 'object',
    nodeType: 'ServiceNode',
    iconClass: 'serviceIco',
  },
  {
    id: 102,
    label: '物模型事件',
    type: 'event',
    group: 'object',
    nodeType: 'EventNode',
    iconClass: 'eventIco',
  },
  {
    id: 103,
    label: '元数据',
    type: 'metadata',
    group: 'object',
    nodeType: 'MetadataNode',
    iconClass: 'metadataIco',
  },
  {
    id: 104,
    label: '数值变量',
    type: 'variable',
    group: 'object',
    nodeType: 'VariableNode',
    iconClass: 'variableIco',
  },
  {
    id: 105,
    label: '随机数',
    type: 'random',
    group: 'object',
    nodeType: 'RandomNode',
    iconClass: 'randomIco',
  },
  {
    id: 200,
    label: '条件判断',
    type: 'judgment',
    group: 'judgment',
    nodeType: 'JudgmentNode',
    iconClass: 'judgmentIco',
  },
  {
    id: 201,
    label: '多分支判断',
    type: 'switch',
    group: 'judgment',
    nodeType: 'SwitchNode',
    iconClass: 'switchIco',
  },
  {
    id: 300,
    label: '加',
    type: 'add',
    group: 'compute',
    nodeType: 'OperatorNode',
    iconClass: 'operatorIco',
  },
  {
    id: 301,
    label: '减',
    type: 'subtract',
    group: 'compute',
    nodeType: 'OperatorNode',
    iconClass: 'operatorIco',
  },
  {
    id: 302,
    label: '乘',
    type: 'multiply',
    group: 'compute',
    nodeType: 'OperatorNode',
    iconClass: 'operatorIco',
  },
  {
    id: 303,
    label: '除',
    type: 'divide',
    group: 'compute',
    nodeType: 'OperatorNode',
    iconClass: 'operatorIco',
  },
  {
    id: 304,
    label: '取余',
    type: 'modular',
    group: 'compute',
    nodeType: 'OperatorNode',
    iconClass: 'operatorIco',
  },
  {
    id: 400,
    label: '日期输出',
    type: 'dateOutput',
    group: 'timer',
    nodeType: 'DateOutputNode',
    iconClass: 'dateIco',
  },
  {
    id: 401,
    label: '日期计算',
    type: 'dateOperator',
    group: 'timer',
    nodeType: 'DateOperatorNode',
    iconClass: 'dateIco',
  },
  {
    id: 402,
    label: '定时器',
    type: 'timer',
    group: 'timer',
    nodeType: 'TimerNode',
    iconClass: 'dateIco',
  },
  {
    id: 403,
    label: '延时器',
    type: 'delay',
    group: 'timer',
    nodeType: 'DelayNode',
    iconClass: 'dateIco',
  },
  {
    id: 404,
    label: '倒计时',
    type: 'countdown',
    group: 'timer',
    nodeType: 'CountdownNode',
    iconClass: 'dateIco',
  },
  {
    id: 500,
    label: '函数',
    type: 'func',
    group: 'function',
    nodeType: 'FuncNode',
    iconClass: 'funcIco',
  },
  {
    id: 501,
    label: '格式转换',
    type: 'format',
    group: 'function',
    nodeType: 'FuncNode',
    iconClass: 'funcIco',
  },
  {
    id: 600,
    label: '执行',
    type: 'parallel',
    group: 'option',
    nodeType: 'ParallelNode',
    iconClass: 'parallelIco',
  },
  {
    id: 601,
    label: '输出',
    type: 'export',
    group: 'option',
    nodeType: 'ExportNode',
    iconClass: 'exportIco',
  },
  {
    id: 700,
    label: '物模型控制',
    type: 'control',
    group: 'execute',
    nodeType: 'ControlNode',
    iconClass: 'controlIco',
  },
  // {
  //   id: 701,
  //   label: '数据存储',
  //   type: 'dataStorage',
  //   group: 'execute',
  //   nodeType: 'DataStorageNode',
  //   iconClass: 'databaseIco',
  // },
  // {
  //   id: 702,
  //   label: '数据推送',
  //   type: 'dataPush',
  //   group: 'execute',
  //   nodeType: 'DataPushNode',
  //   iconClass: 'pushIco',
  // },
  // {
  //   id: 703,
  //   label: '消息推送',
  //   type: 'messagePush',
  //   group: 'execute',
  //   nodeType: 'MessagePushNode',
  //   iconClass: 'messageIco',
  // },
  // {
  //   id: 704,
  //   label: '消息提醒',
  //   type: 'popup',
  //   group: 'execute',
  //   nodeType: 'PopupNode',
  //   iconClass: 'popupIco',
  // },
];

export interface DraggableItemData {
  group: string;
  icon: string;
  node: string;
  type: string;
}
